#!/bin/zsh
# vim: ft=zsh
# Helper functions for the init files
# Eryn Wells <eryn@erynwells.me>


# Print prettier, more uniform messages
function print_msg { print -P "%F{$1}==>%f $2" }
function print_info { print_msg 'blue' "$@" }
function print_error { print_msg 'red' "$@" }

# Return 1 if the binary exists (according to hash); 0 otherwise.
function binary_exists { return $(hash $1 1>/dev/null 2>&1) }
