#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

autoload darwin_icloud_drive_path
autoload darwin_configure_screenshots_directory

function darwin_init_once
{
    # Dim dock icons of apps that have been hidden.
    shell-log "Auto-hiding Dock"
    defaults write com.apple.Dock showhidden -boolean yes
    killall Dock

    darwin_configure_screenshots_directory

    # See https://techstuffer.com/this-app-is-damaged-error-macos-sierra/
    shell-log "Disabling overly restrictive Gatekeeper"
    sudo spctl --master-disable
}

darwin_init_once "$@"
