#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

function g {
    if [[ $# -gt 0 ]]; then
        git $@
    else
        git status --short --branch
    fi
    return $?
}

# Use git completion for the g function
compdef g='git'

g "$@"
