#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

function init-rc-ls
{
    alias la="ls -A $ls_options"
    alias ll="ls -l $ls_options"
    alias l.="ls -d $ls_options .*"

    # Enable ls colors
    export CLICOLOR=1 COLORTERM=1

    # Define colors for ls. See the LSCOLORS documentation in ls(1).
    # The default is "exfxcxdxbxegedabagacadah".
    export LSCOLORS=Exdxcxfxbxegedabagacadah

    local dircolors_bin=$(whence -p dircolors || whence -p gdircolors)
    if [[ -x "$dircolors_bin" ]]; then
        if [[ -f "$HOME/.dircolors/$SYS.cfg" ]]; then
            eval $dircolors_bin "$HOME/.dircolors/$SYS.cfg"
        elif [[ -f "$HOME/.dircolors/default.cfg" ]]; then
            eval $dircolors_bin "$HOME/.dircolors/default.cfg"
        fi
    fi
}

init-rc-ls "$@"
