#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

function init_rc_linux
{
    ShellLog 'Initializing Interactive Environment for Linux'

    alias iptls='sudo iptables --line-numbers -nv -L'
    alias ip6tls='sudo ip6tables --line-numbers -nv -L'
    alias rlx="xrdb $HOME/.Xdefaults"
}

init_rc_linux "$@"
