#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

local pythonRoot
local python27SitePackages

pythonRoot="$HOME/Library/Python"
if [[ -d "$pythonRoot" ]]; then
    for f in `ls "$pythonRoot"`; do
        prepend_to_path "$pythonRoot/$f/bin"
    done
fi

python27SitePackages="$pythonroot/2.7/lib/python/site-packages"
if [[ -d "$python27SitePackages" ]]; then
    if [[ ! -z $PYTHONPATH ]]; then
        PYTHONPATH=$python27SitePackages:$PYTHONPATH
    else
        PYTHONPATH=$python27SitePackages
    fi
fi

export PYTHONPATH

if which virtualenvwrapper.sh 1>/dev/null 2>&1; then
    export WORKON_HOME="$HOME/src/py/.envs"
    source `which virtualenvwrapper.sh`
fi
