#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

# Prefer nvim and vim, in that order, over standard vi, which is insufferable.

if whence -cp nvim &> -; then
    alias vi=nvim
elif whence -cp vim &> -; then
    alias vi=vim
fi
