#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

for x in "$HOME/Code" "$HOME/Documents/Code"; do
    if [[ ! -d "$x" ]]; then
        continue
    fi
    export c="$x"
    break
done

export dd="$HOME/Library/Developer/Xcode/DerivedData"
