#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

autoload -Uz prepend_to_path
autoload -Uz append_to_path

export path=()
append_to_path "/opt/brew/bin"
append_to_path "/opt/homebrew/bin"
append_to_path "/usr/local/bin"
append_to_path "/usr/bin"
append_to_path "/bin"
append_to_path "/usr/local/sbin"
append_to_path "/usr/sbin"
append_to_path "/sbin"
prepend_to_path "/usr/X11/bin"
prepend_to_path "/opt/local/bin"
prepend_to_path "$HOME/.local/bin"
prepend_to_path "$HOME/.cargo/bin"
prepend_to_path "$HOME/.gem/ruby/2.2.0/bin"
prepend_to_path "$HOME/.ghcup/bin"
prepend_to_path "$HOME/.vim/bundle/vim-tidal/bin"
prepend_to_path "$HOME/bin"

rehash
