#!/usr/bin/env zsh
# Initialize the path to a standard default
# Eryn Wells <eryn@erynwells.me>

autoload prepend_to_path
autoload append_to_path

function init_path
{
    export path=()
    append_to_path "/usr/local/bin"
    append_to_path "/usr/bin"
    append_to_path "/bin"
    append_to_path "/usr/local/sbin"
    append_to_path "/usr/sbin"
    append_to_path "/sbin"
    prepend_to_path "/usr/X11/bin"
    prepend_to_path "/opt/local/bin"
    prepend_to_path "$HOME/.local/bin"
    prepend_to_path "$HOME/.gem/ruby/2.2.0/bin"
    prepend_to_path "$HOME/.cargo/bin"
    prepend_to_path "$HOME/bin"
}

init_path
