#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

autoload binary_exists

function init_rc_darwin
{
    alias acls='command ls -le'

    # These things might have been installed by Homebrew, and I like the GNU
    # versions better.
    binary_exists gdircolors && alias dircolors='gdircolors'
    binary_exists gfind      && alias find='gfind'
    binary_exists gnuindent  && alias indent='gnuindent'

    binary_exists gls && init_rc_configure_ls `which gls`

    # ldd doesn't exist on OS X, but otool -L does the same thing.
    alias ldd='otool -L'

    local sounds=/System/Library/Sounds
    alias glass="afplay $sounds/Glass.aiff"
    alias funk="afplay $sounds/Funk.aiff"

    autoload +X darwin_init_once
    autoload +X darwin_icloud_drive_path
    autoload +X darwin_configure_screenshots_directory

    # Open a file/folder in Finder
    alias reveal='open -R'

    alias -s app='open'
    alias -s xcodeproj='open -a Xcode'
}

init_rc_darwin "$@"
