#!/usr/bin/env zsh
# Eryn Wells <eryn@erynwells.me>

local mode=emacs

if [[ -z "$mode" ]]; then
    mode=emacs
fi

function configure_zle_emacs { }
function configure_zle_vim { }

if [[ $mode == 'vim' ]]; then
    bindkey -v
    configure_zle_vim
    zle -A .backward-delete-char vi-backward-delete-char
elif [[ $mode == 'emacs' ]]; then
    bindkey -e
    configure_zle_emacs
fi
