#!/bin/zsh
# Make a Maildir directory
# Eryn Wells <eryn@erynwells.me>

function mkmdir
{
    if [[ $#@ -lt 1 ]]; then
        echo "Usage: $0 [maildir ...]"
        exit 1
    fi

    for d in $@; do
        print_info "Making maildir: $d"
        mkdir -p "$d"/{new,cur,tmp}
    done
}

mkmdir "$@"
