---
- name: Configure ZSH
  import_tasks: zsh.yml

- name: Configure XDG environment
  import_tasks: xdg_home.yml

- name: Configure vim
  import_tasks: vim.yml
- name: Configure neovim
  import_tasks: neovim.yml
