---
- name: Configure macOS
  ansible.builtin.import_tasks: macos/main.yml
  when: ansible_os_family == "macOS"

- name: Configure XDG environment
  ansible.builtin.import_tasks: xdg_home.yml

- name: Configure zsh
  ansible.builtin.import_tasks: zsh.yml

- name: Configure vim
  ansible.builtin.import_tasks: vim.yml
- name: Configure neovim
  ansible.builtin.import_tasks: neovim.yml

- name: Configure git
  ansible.builtin.import_tasks: git.yml

- name: Configure tmux
  ansible.builtin.import_tasks: tmux.yml
