---
- name: "Symlink {{ dotfile_src }}"
  ansible.builtin.file:
    src: "{{ ansible_local.dotfiles.path }}/{{ dotfile_src }}"
    dest: "~/.{{ dotfile_dest | default(dotfile_src) }}"
    owner: "{{ ansible_user_id }}"
    mode: 0644
    state: link
